### ISSUE TITLE
Not working well

### ISSUE THREAD

**Issue by xeruf** [wren/jrnl.vim#2]
So, I am having a few issues in neovim with vim-plug:
- no automatic recognition of .jrnl files
- does not highlight anything except tags

There is a [fork](https://github.com/austintraver/vim-jrnl) that at least highlights dates as well, but that's it.

**Comment by wren** [comment]
Hi! The notification for this fell through the cracks, so I apologize for the slow response.

The automatic recognition of .jrnl files isn't a feature of this repo (although it's a good suggestion).

For the highlighting problems you're having, can you please provide some info about your environment (version numbers, etc)? It would be helpful in order to be able to know what's going on.

**Comment by wren** [comment]
Closing due to lack of info. Please feel free to comment with more info if you'd like to continue the conversation.

**Comment by xeruf** [comment]
Neovim, vim-plug
![image](https://user-images.githubusercontent.com/13354331/157459395-4d811161-7775-4338-9f5b-9a8377601f13.png)
I don't really use headlines, they do work though, as well as the automatic folding. But the timestamps aren't recognised.

**Comment by xeruf** [comment]
For comparison, this is how it looks when viewed with jrnl:
![image](https://user-images.githubusercontent.com/13354331/157459880-0c35e7df-4eff-40dc-83bd-6983ad324757.png)

This is my `.config/jrnl/jrnl.yaml`
```yml
colors:
  body: none
  date: green
  tags: yellow
  title: blue
default_hour: 0
default_minute: 0
editor: nvim +
encrypt: false
highlight: true
indent_character: '|'
linewrap: 99
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %a %H:%M'
version: v2.4.5
```
